### PR TITLE
Load libvalidations in run script

### PR DESCRIPTION
**Pull request by brenix**
**Description of the change**

When calling the run script, the following message is logged

/opt/bitnami/scripts/etcd/run.sh: line 21: is_empty_value: command not found

This should source the shell library which contains this function

### CODE REVIEW

**Comment by marcosbc** [comment]
Good catch @brenix! The change looks fine to me, could you remove the "Draft" tag so it can be merged?

**Comment by brenix** [comment]
Sounds good, yeah I had it in draft as I did not test locally. Feel free to merge if you think it looks good. Thanks!

**Comment by juan131** [comment]
Please don't merge this PR. We're doing a major refactoring at https://github.com/bitnami/bitnami-docker-etcd/pull/13

**Comment by brenix** [comment]
Assuming this is no longer an issue after the refactor. Haven't kept an eye on the recent changes either. Going to close for now

**Pull request closed without merging**
